BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: '0.0'
            font_size: 48
            multiline: False
            on_text: app.handle_calculate()
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.5
            Button:
                text: 'up'
                on_press: app.handle_increment(1)
            Button:
                text: 'down'
                on_press: app.handle_increment(-1)
#    Button:
#        text: "Convert miles to km"
#        on_press: app.handle_calculate()
    Label:
        text: app.output_text
        color: 1, 1, 0, 1